### ISSUE TITLE
Melhorar UI/UX e o template

### ISSUE THREAD

**Issue by mgoulao** [cs-ieee-ist/cs-ieee-ist.github.io#58]
Agora que algumas das disciplinas começam a ter algum conteúdo é necessário melhorar o design da página, torna-lo consistente e corrigir alguns problemas com a navegação.
Como já acabei a minha parte tomei a liberdade fazer um rápido protótipo, fica aqui o [Link](https://xd.adobe.com/spec/4310e8ff-afc7-40b4-757b-b5bd592bb412-3521/).
O design não é muito diferente, apenas tem algumas mudanças nomeadamente nas cores, para melhorar a apresentação do conteúdo.
Feedback é bem vindo, obviamente 😉.

**Comment by OcarinaRedcoat** [comment]
Sim de facto tens razão visto que começamos a ter conteúdo, melhorar o design é um must
Ja vi o prototipo que mandaste está muito fixe, gosto do light theme, não é aberrante aos olhos, e as cores branco e azul fazem sentido de acordo com o logo do IEEE
