### ISSUE TITLE
Prepare website for release

### ISSUE THREAD

**Issue by mgoulao** [cs-ieee-ist/cs-ieee-ist.github.io#76]
Objetivo: Publicar todo o conteúdo que está pronto. Criar mecanismo que esconda todo conteúdo inacabado.

**Comment by OcarinaRedcoat** [comment]
A maneira mais facil é ir ao ficheiro sidenav.html e comentar as secções nao acabadas, assim deixamos de der na sidenav as cadeiras inacabadas e podemos ja publicar o repositorio

**Comment by mgoulao** [comment]
Criei uma nova classe `.dropdown-btn.completed {display: block;}`. Falta agora adicionar algum conteúdo na página Welcome.
